import{a as L,S as b,i as a}from"./assets/vendor-BSTwZ_tR.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const w="52380284-963e8352b908bdb319614297a",v="https://pixabay.com/api/";async function d(o,t){const i={key:w,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};try{return(await L.get(v,{params:i})).data}catch(s){throw s}}const u=document.querySelector(".gallery"),f=document.querySelector(".loader"),m=document.querySelector(".js-load-more"),S=new b(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const t=o.map(({webformatURL:i,largeImageURL:s,tags:e,likes:r,views:n,comments:p,downloads:g})=>`
  <li>
   <a href="${s}">
            <img src="${i}" alt="${e}" width="300"/>
          </a>
 <div class="info">
            <p>👍 ${r}</p>
            <p>👀 ${n}</p>
            <p>💬 ${p}</p>
            <p>⬇️ ${g}</p>
          </div>
  </li>`).join("");u.insertAdjacentHTML("beforeend",t),S.refresh()}function q(){u.innerHTML=""}function P(){f.classList.add("is-visible")}function $(){f.classList.remove("is-visible")}function B(){m.classList.remove("load-more-hidden")}function y(){m.classList.add("load-more-hidden")}let c=1,l="";const E=document.querySelector(".js-load-more"),M=document.querySelector(".form");M.addEventListener("submit",o=>{if(o.preventDefault(),l=o.target.elements["search-text"].value.trim(),c=1,y(),!l){a.error({title:"error",message:"Please enter a search query!"});return}q(),P(),d(l,c).then(t=>{if(t.hits.length===0){a.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}h(t.hits),t.totalHits>15&&B()}).catch(()=>{a.error({title:"Error",message:"Something went wrong. Please try again later."})}).finally(()=>{$()})});E.addEventListener("click",O);async function O(){c+=1;try{const o=await d(l,c);h(o.hits);const{height:t}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),c*15>=o.totalHits&&(y(),a.info({title:"End",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({title:"Error",message:"Something went wrong. Please try again later."})}}
//# sourceMappingURL=index.js.map
