import{a as v,S,i as c}from"./assets/vendor-BSTwZ_tR.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=i(e);fetch(e.href,r)}})();const q="52380284-963e8352b908bdb319614297a",P="https://pixabay.com/api/";async function u(o,t){const i={key:q,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};try{return(await v.get(P,{params:i})).data}catch(a){throw a}}const f=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".js-load-more"),$=new S(".gallery a",{captionsData:"alt",captionDelay:250});function h(o){const t=o.map(({webformatURL:i,largeImageURL:a,tags:e,likes:r,views:n,comments:w,downloads:b})=>`
  <li>
   <a href="${a}">
            <img src="${i}" alt="${e}" width="300"/>
          </a>
 <div class="info">
            <p>👍 ${r}</p>
            <p>👀 ${n}</p>
            <p>💬 ${w}</p>
            <p>⬇️ ${b}</p>
          </div>
  </li>`).join("");f.insertAdjacentHTML("beforeend",t),$.refresh()}function B(){f.innerHTML=""}function p(){m.classList.add("is-visible")}function g(){m.classList.remove("is-visible")}function L(){y.classList.remove("load-more-hidden")}function d(){y.classList.add("load-more-hidden")}let s=1,l="";const E=document.querySelector(".js-load-more"),M=document.querySelector(".form");M.addEventListener("submit",async o=>{if(o.preventDefault(),l=o.target.elements["search-text"].value.trim(),s=1,d(),!l){c.error({title:"error",message:"Please enter a search query!"});return}B(),p();try{const t=await u(l,s);if(t.hits.length===0){c.warning({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!"});return}h(t.hits),t.totalHits>s*15?L():d()}catch{c.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{g()}});E.addEventListener("click",O);async function O(){s+=1,d(),p();try{const o=await u(l,s);h(o.hits);const{height:t}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"}),s*15<o.totalHits?L():(d(),c.info({title:"End",message:"We're sorry, but you've reached the end of search results."}))}catch{c.error({title:"Error",message:"Something went wrong. Please try again later."})}finally{g()}}
//# sourceMappingURL=index.js.map
